### ISSUE TITLE
How do you get the formio file loaded back into the Form.io Builder

### ISSUE THREAD

**Issue by proth1** [softcannery/camunda-formio-accelerator#34]
Hi Camunda Formio Accelerator Team,

Can you please tell me how (if possible) to import the example `parallel_multi-instance_sub-process_demo.formio` file provided with the package into a Stage in the Form.io service at https://portal.form.io/?  Or optionally import it into the open-source version of Form.io.

Thank you very much!

**Comment by softcannery-ltd** [comment]
You can use command shell and `jq` to generate a import template Json file from the exported release template to be able to import it into a project stage at https://portal.form.io/

```sh
cat parallel_multi-instance_sub-process_demo.formio | jq .template > parallel_multi-instance_sub-process_demo.import.
json
```

Then, go to Staging -> Import Template to import ` parallel_multi-instance_sub-process_demo.import.
json` template into your Form.io project stage:

![image](https://github.com/softcannery/camunda-formio-accelerator/assets/140441971/beb9ff44-ee0d-45f4-8a11-4ced40adaa10)

**Comment by proth1** [comment]
That is AWESOME!!  Thank you very much.  That worked flawlessly!!
🙏
