### ISSUE TITLE
Groovy vs. JavaScript

### ISSUE THREAD

**Issue by proth1** [softcannery/camunda-formio-accelerator#35]
I tried to run a process that uses a javascript event listener and got the following error message:

```
The process could not be started. :
Cannot instantiate process definition quoteToClose:2:d88fe0a5-4fd5-11ee-8755-0242ac120005: Can't find scripting engine for 'javascript': scriptEngine is null
```
I assume this means that javascript is not configured for the camunda image packaged with the accelerator.  Is there any issue including javascript?
Thanks,

**Comment by softcannery-ltd** [comment]
The JavaScript support has been removed starting from JDK 15. If your project previously used JavaScript engine provided with JDK 11 for script tasks, you will need to add Nashorn Core dependency to restore Javascript support for script tasks:  https://central.sonatype.com/artifact/org.openjdk.nashorn/nashorn-core/15.4/versions

**Comment by proth1** [comment]
Thank you very much!
