### ISSUE TITLE
how to fix the situation where the default Kermit user is locked out

### ISSUE THREAD

**Issue by proth1** [softcannery/camunda-formio-accelerator#39]
I've somehow managed to lock myself out.

`2023-09-12 02:29:33 2023-09-12 06:29:33.447  INFO 1 --- [           main] org.camunda.bpm.spring.boot              : STARTER-SB011 Skip creating initial Admin User, user does exist: UserEntity[id=kermit, revision=14, firstName=Kermit, lastName=Kermit, email=kermit@localhost, password=******, salt=******, lockExpirationTime=Tue Sep 12 06:25:54 GMT 2023, attempts=10]`

I've tried to reinstall everything and continue to get the above message in the log.

Can you please tell me how to resolve this issue?

Thanks,

**Comment by softcannery-ltd** [comment]
You can always run `make clean` to reset the Docker for Desktop environment and then re-start with `make up logs`
