### ISSUE TITLE
Publish Maven release packages to GitHub Packages

### ISSUE THREAD

**Issue by softcannery-ltd** [softcannery/camunda-formio-accelerator#41]
https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven#publishing-packages-to-github-packages

**Comment by mike-vasylchenko** [comment]
created document - https://github.com/softcannery/camunda-formio-accelerator/wiki/How-to-add-%22camunda%E2%80%90formio%E2%80%90plugin%22-as-a-Maven-dependency
